.TH import-sampleschool 1
.SH NAME
import-sampleschool \- imports sample school data into SchoolTool
.SH SYNOPSIS
.B import-sampleschool
.I "[options]"
.SH DESCRIPTION
.B import-sampleschool
is a script that imports sample school data into a running SchoolTool server.
The server must be running, and it must not contain any data, or the import
will fail.
.SH OPTIONS
.TP
.B \-h HOSTNAME, \-\-host=HOSTNAME
Specify the hostname of the server (default: localhost).
.TP
.B \-p PORT, \-\-port=PORT
Specify the port number of the server (default: 7001).
.SH FILES
.TP
.B /usr/share/schooltool-clients/sampleschool/
Location of sample data files to be imported.
.SH BUGS
The import script performs up to six HTTP requests per object imported and
is very slow.
.SH "SEE ALSO"
schooltool-server(1), schooltool-client(1), wxschooltool(1).
