.TH schooltool-client 1
.SH NAME
schooltool-client \- starts the SchoolTool command-line client
.SH SYNOPSIS
.B schooltool-client
.I "[options]"
.SH DESCRIPTION
.B schooltool-client
is the SchoolTool command-line client program.  It can be used interactively
or it can be scripted.
.PP
You can use the interactive help facility by typing \fBhelp\fP.
.SH OPTIONS
.TP
.B \-h HOSTNAME, \-\-host=HOSTNAME
Specify the hostname of the server (default: localhost).
.TP
.B \-p PORT, \-\-port=PORT
Specify the port number of the server (default: 7001).
.TP
.B \-s, \-\-ssl
Connect to the server with SSL.
.SH BUGS
This manual page does not fully describe the command set of the client.
.SH "SEE ALSO"
schooltool-server(1), wxschooltool(1), import-sampledata(1).
