.TH schooltool-server 1
.SH NAME
schooltool-server \- starts the SchoolTool server
.SH SYNOPSIS
.B schooltool-server
.I "[options]"
.SH DESCRIPTION
.B schooltool-server
is the SchoolTool server program.
.SH OPTIONS
.TP
.B \-h, \-\-help
Show summary of options
.TP
.B \-c FILENAME, \-\-config=FILENAME
Use the given configuration file.
.TP
.B \-d, \-\-daemon
Go to background after starting.
.SH FILES
.TP
.B /etc/schooltool.conf
The default server configuration file
.TP
.B /var/lib/schooltool-server/
The default directory for data files (Debian).
.TP
.B /var/log/schooltool-server/error.log
The default location for the error log file (Debian).
.TP
.B /var/log/schooltool-server/access.log
The default location for the access log file (Debian).
.SH "SEE ALSO"
schooltool-client(1), wxschooltool(1), import-sampledata(1).
