.TH schooltool 1
.SH NAME
schooltool \- starts the SchoolTool server
.SH SYNOPSIS
.B schooltool
.I "[options]"
.SH DESCRIPTION
.B schooltool
is the SchoolTool server program.
.SH OPTIONS
.TP
.B \-h, \-\-help
Show summary of options
.TP
.B \-c FILENAME, \-\-config=FILENAME
Use the given configuration file.
.TP
.B \-d, \-\-daemon
Go to background after starting.
.SH FILES
.TP
.B /etc/schooltool/schooltool.conf
The default server configuration file
.TP
.B /var/lib/schooltool/
The default directory for data files (Debian).
.TP
.B /var/log/schooltool/error.log
The default location for the error log file (Debian).
.TP
.B /var/log/schooltool/web-access.log
The default location for the web access log file (Debian).
.B /var/log/schooltool/rest-access.log
The default location for the REST access log file (Debian).
.SH "SEE ALSO"
schooltool-client(1), wxschooltool(1), import-sampledata(1).
