.TH schoolbell 1
.SH NAME
schoolbell \- starts the SchoolBell server
.SH SYNOPSIS
.B schoolbell
.I "[options]"
.SH DESCRIPTION
.B schoolbell
is the SchoolBell server program.
.SH OPTIONS
.TP
.B \-h, \-\-help
Show summary of options
.TP
.B \-c FILENAME, \-\-config=FILENAME
Use the given configuration file.
.TP
.B \-d, \-\-daemon
Go to background after starting.
.SH FILES
.TP
.B /etc/schoolbell/schoolbell.conf
The default server configuration file
.TP
.B /var/lib/schoolbell/
The default directory for data files (Debian).
.TP
.B /var/log/schoolbell/error.log
The default location for the error log file (Debian).
.TP
.B /var/log/schoolbell/web-access.log
The default location for the web access log file (Debian).
.B /var/log/schoolbell/rest-access.log
The default location for the REST access log file (Debian).
