.TH schooltool-server 1
.SH NAME
schooltool-server \- starts the SchoolTool server
.SH SYNOPSIS
.B schooltool-server
.I "[options]"
.SH DESCRIPTION
.B schooltool-server
is the SchoolTool server program.
.SH OPTIONS
.TP
.B \-h, \-\-help
Show summary of options
.TP
.B \-c FILENAME, \-\-config=FILENAME
Use the given configuration file.
.SH FILES
.TP
.B /etc/schooltool.conf
The default server configuration file
.SH "SEE ALSO"
schooltool-client(1), wxschooltool(1), import-sampledata(1).
