#!/usr/bin/python
"""
A script to start the SchoolBell server in a Debian system.
"""

# Please don't change the following lines unless you look in script.py first
import sys
# paths begin
# paths end
# config begin
# config end

import schooltool.main
schooltool.main.main()
