#!/usr/bin/python
"""
A script to start the SchoolTool server in a Debian system.
"""

# Please don't modify the following lines until you have looked in setup.py
import sys
# paths begin
# paths end
# config begin
# config end

import schooltool.main
schooltool.main.main()
